import {
  antiguedadEnTexto,
  diaDemostracion,
  diasEntre,
  fechaCorta,
  mesYAnio,
  sumarDias,
} from "./format";
import type {
  Atencion,
  Audifono,
  Cita,
  Comunicacion,
  Documento,
  EventoTimeline,
  Paciente,
  Profesional,
  Recordatorio,
  Sucursal,
} from "./types";

/**
 * Día de la demostración: la fecha real en que se abre el prototipo.
 * Nunca se escribe una fecha a mano: todas se derivan de aquí.
 */
const DEMO = diaDemostracion();
export const HOY = DEMO.fecha;
/** Cierto cuando hoy es domingo y la demostración se corrió al lunes. */
export const DEMO_DESPLAZADA = DEMO.desplazadaDesdeDomingo;

/**
 * Fecha con la que se redactó originalmente el conjunto de datos de ejemplo.
 * `rel()` traslada cada fecha semilla conservando exactamente su distancia a esta
 * referencia, de modo que la demostración se ve igual cualquier día que se abra.
 */
const ANCLA = "2026-08-01";

function rel(fechaEjemplo: string): string {
  return sumarDias(HOY, diasEntre(ANCLA, fechaEjemplo));
}

// ─── Sucursal ────────────────────────────────────────────────────────────────
// D-10 resuelta: Proaudio opera únicamente en Ibarra, con una sola sucursal.
// El campo se conserva en el modelo por si en el futuro se abre otra.
export const SUCURSAL_ID = "SUC-01";

export const sucursales: Sucursal[] = [
  { id: SUCURSAL_ID, nombre: "Proaudio Ibarra", ciudad: "Ibarra" },
];

// ─── Catálogos provisionales — "Por validar" con Proaudio ────────────────────
export const MOTIVOS_CITA = [
  "Primera consulta",
  "Control periódico",
  "Audiometría",
  "Adaptación de audífono",
  "Entrega de equipo",
  "Mantenimiento / limpieza",
  "Recepción de reparación",
  "Otro",
]; // ⚠ Lista provisional — D-02

export const DURACIONES_CITA = [15, 20, 30, 40, 45, 60, 75, 90, 120]; // ⚠ Provisionales — D-02

export const TIPOS_ATENCION = [
  "Control periódico",
  "Primera evaluación",
  "Audiometría",
  "Adaptación de audífono",
  "Entrega de equipo",
  "Mantenimiento / limpieza",
  "Revisión por garantía",
  "Otro",
]; // ⚠ Catálogo por validar — D-23

export const TIPOS_DOCUMENTO = [
  "Cartilla física",
  "Resultado de audiometría",
  "Certificado de garantía",
  "Factura o comprobante",
  "Examen externo",
  "Orden médica",
  "Otro",
]; // ⚠ Lista provisional

export const MARCAS_SUGERIDAS = [
  "Marca Demo Uno",
  "Marca Demo Dos",
  "Marca Demo Tres",
]; // ⚠ Marcas ficticias — la lista real debe darla Proaudio

export const ESTADOS_DIGITALIZACION = [
  "Sin digitalizar",
  "Datos básicos",
  "Parcial",
  "Completa para operar",
  "Completa",
] as const;

/**
 * Agencias Proaudio. Pedido por Karla Chamba el 6 ago 2026: usar esta lista tanto
 * para la agencia de referencia del paciente como para la agencia donde se
 * adquirió un audífono. Solo Ibarra opera en este sistema (D-10), pero un
 * paciente puede haber adquirido su equipo en otra agencia de la cadena.
 * ⚠ Lista provisional — confirmar el listado completo y los nombres exactos con Proaudio.
 */
export const AGENCIAS = ["Ibarra", "Quito", "Otra agencia Proaudio"]; // ⚠ Lista provisional

// ─── Equipo de Proaudio ──────────────────────────────────────────────────────
// Nombres reales del personal. Los pacientes, en cambio, son todos ficticios.
export const profesionales: Profesional[] = [
  {
    id: "PRO-01",
    nombre: "María Fernanda Terán",
    nombreCorto: "M. F. Terán",
    iniciales: "MT",
    rol: "Audiología",
    sucursalId: SUCURSAL_ID,
    color: "border-sky-400 bg-sky-50",
    atiende: true,
  },
  {
    id: "PRO-02",
    nombre: "Karla Chamba",
    nombreCorto: "K. Chamba",
    iniciales: "KC",
    rol: "Audiología",
    sucursalId: SUCURSAL_ID,
    color: "border-emerald-400 bg-emerald-50",
    atiende: true,
  },
  {
    id: "PRO-05",
    nombre: "Gonzalo Realpe",
    nombreCorto: "G. Realpe",
    iniciales: "GR",
    rol: "Audiología",
    sucursalId: SUCURSAL_ID,
    color: "border-violet-400 bg-violet-50",
    atiende: true,
  },
  {
    id: "PRO-03",
    nombre: "Mayra Lechón",
    nombreCorto: "M. Lechón",
    iniciales: "ML",
    rol: "Recepción",
    sucursalId: SUCURSAL_ID,
    color: "border-slate-300 bg-slate-50",
    atiende: true,
  },
  {
    id: "PRO-04",
    nombre: "Diego Peñafiel",
    nombreCorto: "D. Peñafiel",
    iniciales: "DP",
    rol: "Administración",
    sucursalId: SUCURSAL_ID,
    color: "border-slate-300 bg-slate-50",
    atiende: false,
    ficticio: true,
  },
];

// ─── Pacientes (todos ficticios) ─────────────────────────────────────────────
const F_ULT_ROSA = rel("2026-04-28");
const F_ULT_SEGUNDO = rel("2025-05-15");
const F_VENC_GARANTIA_ROSA = rel("2026-08-13");
const F_REPARACION_LISTA = rel("2026-07-30");

export const pacientesSeed: Paciente[] = [
  {
    id: "PAC-00412",
    nombres: "Rosa",
    apellidos: "Cabascango",
    telefono: "099-000-0001",
    telefonoFamiliar: "099-000-0021",
    documento: "DOC-FICT-001",
    fichaFisica: "128",
    ciudad: "Ibarra",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-01",
    categoria: "A",
    estado: "Activa",
    estadoDigitalizacion: "Parcial",
    ubicacionArchivo: "Estante 4 · carpeta 128",
    fechaPrimeraVisita: rel("2024-08-02"),
    ultimaVisita: F_ULT_ROSA,
    ultimaIndicacion:
      "Continuar con uso diario. Limpiar el molde cada semana. Volver a control en 3 meses.",
    proximaAccion: `Control periódico · sugerido para ${mesYAnio(HOY)}`,
    alerta: `Garantía del audífono vence el ${fechaCorta(F_VENC_GARANTIA_ROSA)} (fechas ficticias para validación visual)`,
  },
  {
    id: "PAC-01187",
    nombres: "Segundo",
    apellidos: "Chalá",
    telefono: "099-000-0002",
    documento: "DOC-FICT-002",
    fichaFisica: "233",
    ciudad: "Ibarra",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-02",
    categoria: "B",
    estado: `Sin visita hace ${antiguedadEnTexto(F_ULT_SEGUNDO, HOY)} — regla temporal por validar con Proaudio`,
    estadoDigitalizacion: "Datos básicos",
    ubicacionArchivo: "Estante 6 · carpeta 233",
    fechaPrimeraVisita: rel("2024-11-20"),
    ultimaVisita: F_ULT_SEGUNDO,
    ultimaIndicacion: "Revisar adaptación en 6 meses. Uso progresivo del equipo.",
    proximaAccion: `Contactar: no registra visitas desde ${mesYAnio(F_ULT_SEGUNDO)}`,
    alerta: `Sin visita desde ${mesYAnio(F_ULT_SEGUNDO)} (${antiguedadEnTexto(F_ULT_SEGUNDO, HOY)}) — Regla temporal por validar con Proaudio`,
  },
  {
    id: "PAC-00976",
    nombres: "Marina",
    apellidos: "Pozo",
    telefono: "099-000-0003",
    ciudad: "Otavalo",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-02",
    categoria: "A",
    estado: "Activa",
    estadoDigitalizacion: "Completa para operar",
    ubicacionArchivo: "Estante 2 · carpeta 87",
    fichaFisica: "87",
    fechaPrimeraVisita: rel("2023-09-10"),
    ultimaVisita: rel("2026-02-12"),
    ultimaIndicacion: "Continuar uso habitual. Control en 6 meses.",
    proximaAccion: `Control periódico · ${mesYAnio(HOY)}`,
  },
  {
    id: "PAC-01542",
    nombres: "Jorge",
    apellidos: "Almeida",
    telefono: "099-000-0004",
    ciudad: "Ibarra",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-05",
    estado: "Paciente nuevo",
    estadoDigitalizacion: "Sin digitalizar",
    fechaPrimeraVisita: HOY,
    proximaAccion: "Primera consulta hoy 10:30",
    esNuevo: true,
    comoConocio: "Referido por un paciente",
    referidoPor: "Rosa Cabascango (PAC-00412)",
  },
  {
    id: "PAC-00238",
    nombres: "Blanca",
    apellidos: "Yépez",
    telefono: "099-000-0005",
    telefonoFamiliar: "099-000-0022",
    correo: "ejemplo@prototipo.invalid",
    ciudad: "Ibarra",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-02",
    categoria: "S+",
    estado: "Activa",
    estadoDigitalizacion: "Parcial",
    ubicacionArchivo: "Caja 3 · carpeta 41",
    fichaFisica: "41",
    fechaPrimeraVisita: rel("2023-09-10"),
    ultimaVisita: rel("2025-08-05"),
    ultimaIndicacion: "Audiometría de control en un año.",
    proximaAccion: `Audiometría anual · ${mesYAnio(HOY)}`,
    alerta: "Audiometría anual pendiente (plazo de ejemplo, por validar)",
  },
  {
    id: "PAC-01903",
    nombres: "Luis",
    apellidos: "Ipiales",
    telefono: "099-000-0006",
    ciudad: "Atuntaqui",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-05",
    categoria: "A",
    estado: "Activo",
    estadoDigitalizacion: "Parcial",
    ubicacionArchivo: "Estante 5 · carpeta 310",
    fichaFisica: "310",
    fechaPrimeraVisita: rel("2025-03-01"),
    ultimaVisita: rel("2026-07-22"),
    ultimaIndicacion: "Dejó su equipo para reparación. Avisaremos cuando esté listo.",
    proximaAccion: "Entrega de equipo reparado · cita de hoy 12:00",
    alerta: `Equipo reparado listo para entregar desde el ${fechaCorta(F_REPARACION_LISTA)}`,
  },
  {
    id: "PAC-00733",
    nombres: "María",
    apellidos: "Farinango",
    telefono: "099-000-0007",
    ciudad: "Cotacachi",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-01",
    categoria: "B",
    estado: "Activa",
    estadoDigitalizacion: "Datos básicos",
    fichaFisica: "412",
    fechaPrimeraVisita: rel("2024-11-20"),
    ultimaVisita: rel("2026-05-13"),
    ultimaIndicacion: "Control en 3 meses.",
    proximaAccion: `Control periódico · ${mesYAnio(rel("2026-08-13"))}`,
  },
  {
    id: "PAC-01050",
    nombres: "Antonio",
    apellidos: "Guamán",
    telefono: "099-000-0008",
    telefonoFamiliar: "099-000-0023",
    ciudad: "Ibarra",
    sucursalId: SUCURSAL_ID,
    profesionalId: "PRO-05",
    estado: "Activo",
    estadoDigitalizacion: "Datos básicos",
    fichaFisica: "509",
    fechaPrimeraVisita: rel("2024-08-02"),
    ultimaVisita: rel("2025-08-20"),
    ultimaIndicacion: "Audiometría de control en un año.",
    proximaAccion: `Audiometría anual · ${mesYAnio(HOY)}`,
  },
];

// ─── Citas ───────────────────────────────────────────────────────────────────
// Repartidas entre las tres personas que atienden.
export const citasSeed: Cita[] = [
  {
    id: "CIT-101",
    pacienteId: "PAC-00412",
    fecha: HOY,
    hora: "09:00",
    duracionMin: 30,
    profesionalId: "PRO-01",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Confirmada",
  },
  {
    id: "CIT-102",
    pacienteId: "PAC-00976",
    fecha: HOY,
    hora: "09:45",
    duracionMin: 30,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Confirmada",
  },
  {
    id: "CIT-103",
    pacienteId: "PAC-01542",
    fecha: HOY,
    hora: "10:30",
    duracionMin: 45,
    profesionalId: "PRO-05",
    sucursalId: SUCURSAL_ID,
    motivo: "Primera consulta",
    estado: "Agendada",
  },
  {
    id: "CIT-104",
    pacienteId: "PAC-01903",
    fecha: HOY,
    hora: "12:00",
    duracionMin: 20,
    profesionalId: "PRO-05",
    sucursalId: SUCURSAL_ID,
    motivo: "Entrega de equipo",
    estado: "Confirmada",
  },
  {
    id: "CIT-105",
    pacienteId: "PAC-00238",
    fecha: rel("2026-08-02"),
    hora: "11:15",
    duracionMin: 45,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Audiometría",
    estado: "Agendada",
  },
  {
    id: "CIT-106",
    pacienteId: "PAC-00733",
    fecha: rel("2026-08-05"),
    hora: "10:00",
    duracionMin: 30,
    profesionalId: "PRO-01",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Agendada",
  },
  {
    id: "CIT-107",
    pacienteId: "PAC-01050",
    fecha: rel("2026-08-07"),
    hora: "15:00",
    duracionMin: 45,
    profesionalId: "PRO-05",
    sucursalId: SUCURSAL_ID,
    motivo: "Audiometría",
    estado: "Agendada",
  },
  // Historial
  {
    id: "CIT-090",
    pacienteId: "PAC-00412",
    fecha: F_ULT_ROSA,
    hora: "10:00",
    duracionMin: 30,
    profesionalId: "PRO-01",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Completada",
  },
  {
    id: "CIT-080",
    pacienteId: "PAC-00412",
    fecha: rel("2025-12-12"),
    hora: "11:00",
    duracionMin: 30,
    profesionalId: "PRO-01",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Completada",
  },
  {
    id: "CIT-070",
    pacienteId: "PAC-00412",
    fecha: rel("2025-09-05"),
    hora: "09:30",
    duracionMin: 45,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Audiometría",
    estado: "Completada",
  },
  {
    id: "CIT-060",
    pacienteId: "PAC-00412",
    fecha: rel("2025-06-20"),
    hora: "10:00",
    duracionMin: 30,
    profesionalId: "PRO-01",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "No atendida",
    motivoCambio: "No asistió. Sin aviso previo.",
  },
  {
    id: "CIT-050",
    pacienteId: "PAC-01187",
    fecha: F_ULT_SEGUNDO,
    hora: "09:00",
    duracionMin: 30,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Completada",
  },
  {
    id: "CIT-095",
    pacienteId: "PAC-01903",
    fecha: rel("2026-07-22"),
    hora: "16:00",
    duracionMin: 15,
    profesionalId: "PRO-05",
    sucursalId: SUCURSAL_ID,
    motivo: "Recepción de reparación",
    estado: "Completada",
  },
  {
    id: "CIT-096",
    pacienteId: "PAC-00976",
    fecha: rel("2026-02-12"),
    hora: "11:30",
    duracionMin: 30,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Control periódico",
    estado: "Completada",
  },
  {
    id: "CIT-097",
    pacienteId: "PAC-00238",
    fecha: rel("2025-08-05"),
    hora: "10:30",
    duracionMin: 45,
    profesionalId: "PRO-02",
    sucursalId: SUCURSAL_ID,
    motivo: "Audiometría",
    estado: "Completada",
  },
];

// ─── Atenciones ──────────────────────────────────────────────────────────────
export const atencionesSeed: Atencion[] = [
  {
    id: "ATN-01",
    pacienteId: "PAC-00412",
    citaId: "CIT-090",
    fecha: F_ULT_ROSA,
    profesionalId: "PRO-01",
    tipo: "Control periódico",
    observacion:
      "Paciente refiere buena adaptación. Se revisa el equipo y se realiza limpieza. Sin novedades.",
    indicacion:
      "Continuar con uso diario. Limpiar el molde cada semana. Volver a control en 3 meses.",
    proximaAccion: "Control periódico",
    fechaSeguimiento: HOY,
    responsableId: "PRO-03",
  },
  {
    id: "ATN-02",
    pacienteId: "PAC-00412",
    citaId: "CIT-080",
    fecha: rel("2025-12-12"),
    profesionalId: "PRO-01",
    tipo: "Control periódico",
    observacion: "Se ajusta programación. Paciente refiere mejoría en ambientes ruidosos.",
    indicacion: "Continuar uso habitual.",
    proximaAccion: "Control periódico",
    fechaSeguimiento: F_ULT_ROSA,
    responsableId: "PRO-03",
  },
  {
    id: "ATN-03",
    pacienteId: "PAC-01187",
    citaId: "CIT-050",
    fecha: F_ULT_SEGUNDO,
    profesionalId: "PRO-02",
    tipo: "Control periódico",
    observacion: "Adaptación en curso. Se recomienda uso progresivo del equipo.",
    indicacion: "Revisar adaptación en 6 meses.",
    proximaAccion: "Control de adaptación",
    fechaSeguimiento: rel("2025-11-15"),
    responsableId: "PRO-03",
  },
  {
    id: "ATN-04",
    pacienteId: "PAC-00976",
    citaId: "CIT-096",
    fecha: rel("2026-02-12"),
    profesionalId: "PRO-02",
    tipo: "Control periódico",
    observacion: "Sin novedades. Equipo en buen estado.",
    indicacion: "Continuar uso habitual. Control en 6 meses.",
    proximaAccion: "Control periódico",
    fechaSeguimiento: rel("2026-08-12"),
    responsableId: "PRO-03",
  },
  {
    id: "ATN-05",
    pacienteId: "PAC-00238",
    citaId: "CIT-097",
    fecha: rel("2025-08-05"),
    profesionalId: "PRO-02",
    tipo: "Audiometría",
    observacion: "Se realiza audiometría de control. Resultado adjunto (documento ficticio).",
    indicacion: "Audiometría de control en un año.",
    proximaAccion: "Audiometría anual",
    fechaSeguimiento: rel("2026-08-05"),
    responsableId: "PRO-03",
  },
  {
    id: "ATN-06",
    pacienteId: "PAC-01903",
    citaId: "CIT-095",
    fecha: rel("2026-07-22"),
    profesionalId: "PRO-05",
    tipo: "Recepción de reparación",
    observacion: "Se recibe equipo con falla de ejemplo. Se envía a revisión técnica (simulado).",
    indicacion: "Avisaremos cuando el equipo esté listo.",
    proximaAccion: "Entregar equipo reparado",
    fechaSeguimiento: HOY,
    responsableId: "PRO-03",
  },
];

// ─── Audífonos ───────────────────────────────────────────────────────────────
export const audifonosSeed: Audifono[] = [
  {
    id: "AUD-01",
    pacienteId: "PAC-00412",
    marca: "Marca Demo Uno",
    modelo: "Modelo Z-1",
    oido: "Derecho",
    serie: "SERIE-DEMO-001",
    fechaEntrega: rel("2024-08-13"),
    estado: "En uso",
    procedencia: "Adquirido en Proaudio",
    numeroFactura: "FACT-DEMO-001",
    garantia: { inicio: rel("2024-08-13"), vencimiento: F_VENC_GARANTIA_ROSA },
  },
  {
    id: "AUD-02",
    pacienteId: "PAC-01903",
    marca: "Marca Demo Dos",
    modelo: "Modelo K-4",
    oido: "Izquierdo",
    serie: "SERIE-DEMO-002",
    fechaEntrega: rel("2025-03-01"),
    estado: "En reparación",
    procedencia: "Adquirido en Proaudio",
    numeroFactura: "FACT-DEMO-002",
    observaciones: "Reparación terminada (simulada). Listo para entregar.",
    garantia: { inicio: rel("2025-03-01"), vencimiento: rel("2027-03-01") },
  },
  {
    id: "AUD-03",
    pacienteId: "PAC-00238",
    marca: "Marca Demo Uno",
    modelo: "Modelo M-3",
    oido: "Ambos",
    serie: "SERIE-DEMO-003",
    fechaEntrega: rel("2023-09-10"),
    estado: "En uso",
    procedencia: "Adquirido en Proaudio",
    numeroFactura: "FACT-DEMO-003",
    garantia: { inicio: rel("2023-09-10"), vencimiento: rel("2025-09-10") },
  },
  {
    id: "AUD-04",
    pacienteId: "PAC-01187",
    marca: "Marca Demo Tres",
    modelo: "Modelo B-2",
    oido: "Derecho",
    serie: "SERIE-DEMO-004",
    fechaEntrega: rel("2024-11-20"),
    estado: "En uso",
    procedencia: "Adquirido en Proaudio",
    numeroFactura: "FACT-DEMO-004",
    garantia: { inicio: rel("2024-11-20"), vencimiento: rel("2026-11-20") },
  },
  {
    // Ejemplo de equipo que el paciente ya traía de otra empresa.
    id: "AUD-05",
    pacienteId: "PAC-01050",
    marca: "Marca Demo Tres",
    modelo: "Modelo T-9",
    oido: "Ambos",
    fechaEntrega: rel("2024-08-02"),
    estado: "En uso",
    procedencia: "Traído de otra empresa",
    observaciones: "El paciente llegó usando este equipo. Sin documentación de compra.",
  },
];

// ─── Documentos ──────────────────────────────────────────────────────────────
export const documentosSeed: Documento[] = [
  {
    id: "DOC-01",
    pacienteId: "PAC-00412",
    tipo: "Resultado de audiometría",
    titulo: `Audiometría ${fechaCorta(rel("2025-09-05"))} (documento ficticio)`,
    fechaDocumento: rel("2025-09-05"),
    fechaCarga: rel("2025-09-05"),
    cargadoPorId: "PRO-02",
  },
  {
    id: "DOC-02",
    pacienteId: "PAC-00412",
    tipo: "Cartilla física",
    titulo: "Cartilla física — página 1 (documento ficticio)",
    fechaDocumento: rel("2024-08-02"),
    fechaCarga: F_ULT_ROSA,
    cargadoPorId: "PRO-03",
  },
  {
    id: "DOC-03",
    pacienteId: "PAC-00412",
    tipo: "Certificado de garantía",
    titulo: "Certificado de garantía (documento ficticio)",
    fechaDocumento: rel("2024-08-13"),
    fechaCarga: F_ULT_ROSA,
    cargadoPorId: "PRO-03",
  },
  {
    id: "DOC-04",
    pacienteId: "PAC-00238",
    tipo: "Resultado de audiometría",
    titulo: `Audiometría ${fechaCorta(rel("2025-08-05"))} (documento ficticio)`,
    fechaDocumento: rel("2025-08-05"),
    fechaCarga: rel("2025-08-05"),
    cargadoPorId: "PRO-02",
  },
  {
    id: "DOC-05",
    pacienteId: "PAC-01903",
    tipo: "Otro",
    titulo: "Orden de reparación (documento ficticio)",
    fechaDocumento: rel("2026-07-22"),
    fechaCarga: rel("2026-07-22"),
    cargadoPorId: "PRO-03",
  },
];

// ─── Recordatorios ───────────────────────────────────────────────────────────
export const recordatoriosSeed: Recordatorio[] = [
  {
    id: "REC-01",
    tipo: "Paciente que dejó de asistir",
    categoria: "Tarea para recepción",
    pacienteId: "PAC-01187",
    motivo: `Sin visita desde ${mesYAnio(F_ULT_SEGUNDO)} (${antiguedadEnTexto(F_ULT_SEGUNDO, HOY)}) — Regla temporal por validar con Proaudio. Contactar para conocer su situación.`,
    fecha: rel("2026-07-20"),
    responsableId: "PRO-03",
    prioridad: "Alta",
    estado: "Pendiente",
    canal: "Llamada",
  },
  {
    id: "REC-02",
    tipo: "Garantía próxima a vencer",
    categoria: "Tarea para recepción",
    pacienteId: "PAC-00412",
    motivo: `La garantía del equipo (SERIE-DEMO-001) vence el ${fechaCorta(F_VENC_GARANTIA_ROSA)} — fechas ficticias para validación visual. Avisar a la paciente.`,
    fecha: HOY,
    responsableId: "PRO-03",
    prioridad: "Alta",
    estado: "Pendiente",
    canal: "Llamada · WhatsApp (Fase futura)",
  },
  {
    id: "REC-03",
    tipo: "Cita pendiente de confirmación",
    categoria: "Recordatorio de cita",
    pacienteId: "PAC-00238",
    motivo: `Confirmar cita del ${fechaCorta(rel("2026-08-02"))} 11:15 (Audiometría · K. Chamba).`,
    fecha: HOY,
    responsableId: "PRO-03",
    prioridad: "Media",
    estado: "Pendiente",
    canal: "Llamada",
  },
  {
    id: "REC-04",
    tipo: "Reparación terminada",
    categoria: "Tarea para recepción",
    pacienteId: "PAC-01903",
    motivo: `Equipo listo desde el ${fechaCorta(F_REPARACION_LISTA)}. Avisar que puede retirar. Tiene cita hoy 12:00.`,
    fecha: HOY,
    responsableId: "PRO-03",
    prioridad: "Media",
    estado: "Pendiente",
    canal: "Llamada",
  },
  {
    id: "REC-05",
    tipo: "Bienvenida a paciente nuevo",
    categoria: "Comunicación futura al paciente",
    pacienteId: "PAC-01542",
    motivo:
      "Primera consulta hoy 10:30. El mensaje de bienvenida automático es Fase futura; hoy es una tarea interna.",
    fecha: HOY,
    responsableId: "PRO-03",
    prioridad: "Baja",
    estado: "Pendiente",
    canal: "WhatsApp (Fase futura)",
  },
  {
    id: "REC-06",
    tipo: "Control periódico",
    categoria: "Tarea para recepción",
    pacienteId: "PAC-00733",
    motivo: "Corresponde control periódico según la última atención. Ofrecer cita.",
    fecha: rel("2026-08-13"),
    responsableId: "PRO-03",
    prioridad: "Media",
    estado: "Pendiente",
    canal: "Llamada",
  },
  {
    id: "REC-07",
    tipo: "Audiometría anual",
    categoria: "Alerta para profesional",
    pacienteId: "PAC-01050",
    motivo: "Se acerca el año desde la última audiometría (plazo de ejemplo, por validar).",
    fecha: rel("2026-08-18"),
    responsableId: "PRO-05",
    prioridad: "Media",
    estado: "Pendiente",
    canal: "Interno",
  },
  {
    id: "REC-08",
    tipo: "Cita pendiente de confirmación",
    categoria: "Recordatorio de cita",
    pacienteId: "PAC-00976",
    motivo: `Confirmar cita del ${fechaCorta(HOY)} 09:45. Confirmada por teléfono.`,
    fecha: rel("2026-07-30"),
    responsableId: "PRO-03",
    prioridad: "Media",
    estado: "Completado",
    canal: "Llamada",
    nota: "Paciente confirmó asistencia.",
  },
];

// ─── Comunicaciones ──────────────────────────────────────────────────────────
export const comunicacionesSeed: Comunicacion[] = [
  {
    id: "COM-01",
    pacienteId: "PAC-00412",
    fecha: rel("2026-07-24"),
    canal: "Llamada",
    resultado: "Contactado",
    nota: `Contactada. Confirmó su cita del ${fechaCorta(HOY)}.`,
    registradoPorId: "PRO-03",
  },
  {
    id: "COM-02",
    pacienteId: "PAC-00976",
    fecha: rel("2026-07-30"),
    canal: "Llamada",
    resultado: "Contactado",
    nota: `Confirmó asistencia a la cita del ${fechaCorta(HOY)}.`,
    registradoPorId: "PRO-03",
  },
];

// ─── Línea de tiempo ─────────────────────────────────────────────────────────
export const eventosSeed: EventoTimeline[] = [
  // Rosa Cabascango
  {
    id: "EVT-01",
    pacienteId: "PAC-00412",
    fecha: HOY,
    tipo: "Cita",
    titulo: "Cita agendada · Control periódico · 09:00 · M. F. Terán",
    detalle: "Estado: Confirmada",
    autor: "Mayra Lechón",
    refId: "CIT-101",
  },
  {
    id: "EVT-02",
    pacienteId: "PAC-00412",
    fecha: rel("2026-07-24"),
    tipo: "Contacto",
    titulo: "Contacto · Llamada",
    detalle: `Resultado: Contactada. Confirmó su cita del ${fechaCorta(HOY)}.`,
    autor: "Mayra Lechón",
  },
  {
    id: "EVT-03",
    pacienteId: "PAC-00412",
    fecha: F_ULT_ROSA,
    tipo: "Atención",
    titulo: "Atención · Control periódico · María Fernanda Terán",
    autor: "M. F. Terán",
    refId: "ATN-01",
  },
  {
    id: "EVT-04",
    pacienteId: "PAC-00412",
    fecha: rel("2025-12-12"),
    tipo: "Atención",
    titulo: "Atención · Control periódico · María Fernanda Terán",
    autor: "M. F. Terán",
    refId: "ATN-02",
  },
  {
    id: "EVT-05",
    pacienteId: "PAC-00412",
    fecha: rel("2025-09-05"),
    tipo: "Documento",
    titulo: "Audiometría realizada · documento adjunto (ficticio)",
    autor: "K. Chamba",
    refId: "DOC-01",
  },
  {
    id: "EVT-06",
    pacienteId: "PAC-00412",
    fecha: rel("2025-06-20"),
    tipo: "Cita",
    titulo: "Cita no atendida · Control periódico",
    detalle: "No asistió. Sin aviso previo.",
    autor: "Mayra Lechón",
    refId: "CIT-060",
  },
  {
    id: "EVT-07",
    pacienteId: "PAC-00412",
    fecha: rel("2024-08-13"),
    tipo: "Equipo",
    titulo: "Entrega de equipo · Marca Demo Uno Modelo Z-1 · Oído derecho · SERIE-DEMO-001",
    detalle: `Garantía hasta ${fechaCorta(F_VENC_GARANTIA_ROSA)} · Factura FACT-DEMO-001 (fechas y reglas ficticias para validación visual)`,
    autor: "M. F. Terán",
    refId: "AUD-01",
  },
  {
    id: "EVT-08",
    pacienteId: "PAC-00412",
    fecha: rel("2024-08-02"),
    tipo: "Ficha",
    titulo: "Ficha creada",
    autor: "Mayra Lechón",
  },
  // Segundo Chalá
  {
    id: "EVT-10",
    pacienteId: "PAC-01187",
    fecha: rel("2026-07-20"),
    tipo: "Recordatorio",
    titulo: `Tarea creada: contactar — sin visita desde ${mesYAnio(F_ULT_SEGUNDO)}`,
    detalle: "Regla temporal por validar con Proaudio",
    autor: "Sistema (simulado)",
  },
  {
    id: "EVT-11",
    pacienteId: "PAC-01187",
    fecha: F_ULT_SEGUNDO,
    tipo: "Atención",
    titulo: "Atención · Control periódico · Karla Chamba",
    autor: "K. Chamba",
    refId: "ATN-03",
  },
  {
    id: "EVT-12",
    pacienteId: "PAC-01187",
    fecha: rel("2024-11-20"),
    tipo: "Equipo",
    titulo: "Entrega de equipo · Marca Demo Tres Modelo B-2 · SERIE-DEMO-004",
    autor: "K. Chamba",
    refId: "AUD-04",
  },
  // Marina Pozo
  {
    id: "EVT-20",
    pacienteId: "PAC-00976",
    fecha: rel("2026-07-30"),
    tipo: "Contacto",
    titulo: `Contacto · Llamada — confirmó cita del ${fechaCorta(HOY)}`,
    autor: "Mayra Lechón",
  },
  {
    id: "EVT-21",
    pacienteId: "PAC-00976",
    fecha: rel("2026-02-12"),
    tipo: "Atención",
    titulo: "Atención · Control periódico · Karla Chamba",
    autor: "K. Chamba",
    refId: "ATN-04",
  },
  // Jorge Almeida
  {
    id: "EVT-30",
    pacienteId: "PAC-01542",
    fecha: rel("2026-07-28"),
    tipo: "Ficha",
    titulo: "Ficha creada · paciente nuevo",
    detalle: "Referido por Rosa Cabascango (PAC-00412)",
    autor: "Mayra Lechón",
  },
  {
    id: "EVT-31",
    pacienteId: "PAC-01542",
    fecha: HOY,
    tipo: "Cita",
    titulo: "Cita agendada · Primera consulta · 10:30 · G. Realpe",
    autor: "Mayra Lechón",
    refId: "CIT-103",
  },
  // Blanca Yépez
  {
    id: "EVT-40",
    pacienteId: "PAC-00238",
    fecha: rel("2026-08-02"),
    tipo: "Cita",
    titulo: "Cita agendada · Audiometría · 11:15 · K. Chamba",
    detalle: "Pendiente de confirmar",
    autor: "Mayra Lechón",
    refId: "CIT-105",
  },
  {
    id: "EVT-41",
    pacienteId: "PAC-00238",
    fecha: rel("2025-08-05"),
    tipo: "Atención",
    titulo: "Atención · Audiometría · Karla Chamba",
    autor: "K. Chamba",
    refId: "ATN-05",
  },
  // Luis Ipiales
  {
    id: "EVT-50",
    pacienteId: "PAC-01903",
    fecha: F_REPARACION_LISTA,
    tipo: "Recordatorio",
    titulo: "Equipo reparado listo para entregar (simulado)",
    autor: "Sistema (simulado)",
  },
  {
    id: "EVT-51",
    pacienteId: "PAC-01903",
    fecha: rel("2026-07-22"),
    tipo: "Atención",
    titulo: "Atención · Recepción de reparación · Gonzalo Realpe",
    autor: "G. Realpe",
    refId: "ATN-06",
  },
  // Antonio Guamán — equipo traído de otra empresa
  {
    id: "EVT-60",
    pacienteId: "PAC-01050",
    fecha: rel("2024-08-02"),
    tipo: "Equipo",
    titulo: "Equipo registrado · Marca Demo Tres Modelo T-9 · Traído de otra empresa",
    detalle: "El paciente llegó usando este equipo. Sin documentación de compra.",
    autor: "G. Realpe",
    refId: "AUD-05",
  },
];